name: Run tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run integration tests
        run: ./gradlew test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          detailed_summary: true
          follow_symlink: true
          check_name: |
            adventure
            shared
            paper
          report_paths: |
            **/adventure/build/test-results/test/TEST-*.xml
            **/shared/build/test-results/test/TEST-*.xml
            **/paper/build/test-results/test/TEST-*.xml
      - name: Publish Test Report
        uses: test-summary/action@v2
        if: success() || failure()
        with:
          paths: |
            **/adventure/build/test-results/test/TEST-*.xml
            **/shared/build/test-results/test/TEST-*.xml
            **/paper/build/test-results/test/TEST-*.xml