name: Update html redirection page

on:
  workflow_call:
    inputs:
      VERSION:
        description: 'Version name'
        required: true
        type: string

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write
  pages: write
  id-token: write

jobs:
  update_html:
    runs-on: ubuntu-latest
    env:
      version: ${{ inputs.VERSION }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle git
        run: |
          git reset --hard
          git fetch origin
          git checkout -b gh-pages origin/gh-pages || git checkout -b gh-pages
          git pull origin gh-pages || true

      - name: Update HTML
        run: |
          sed -i 's|url=https://idankoblik.github.io/Jukebox/[^/]*/">|url=https://idankoblik.github.io/Jukebox/'"$version"'/">|' "index.html"
          git add index.html
          git commit -m "Update index.html"