name: Update html redirection page

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write
  pages: write
  id-token: write

jobs:
  update_html:
    runs-on: ubuntu-latest
    env:
      version: ${{ github.event.inputs.name }}
    steps:
      - name: Checkout Repository
        run: |
          git reset --hard
          git fetch origin
          git checkout -b gh-pages origin/gh-pages || git checkout -b gh-pages
          git pull origin gh-pages || true

      - name: Update HTML
        run: |
          sed -i 's|url=https://cocoa-beans.apartium.net/[^/]*/">|url=https://cocoa-beans.apartium.net/'"$version"'/">|' "index.html"
          git add index.html
          git commit -m "Update index.html"