name: Export changelog

on:
  workflow_call:
    inputs:
      VERSION:
        description: 'Version name'
        required: true
        type: string
    secrets:
      GH_PAGES_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  export_changelog:
    runs-on: ubuntu-latest
    env:
      TARGET_VERSION: ${{ inputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_TOKEN }}

      - name: Setup git
        run: |
          git remote rm origin
          git remote add origin git@github.com:${{ github.repository }}
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: create tag
        run: |
          git tag $TARGET_VERSION
          git push origin $TARGET_VERSION

      - name: export change and create temp file
        run: sh build-scripts/export-changelog.sh

      - name: release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: ${{ inputs.VERSION }}
            body_path: CHANGELOG_temp.md