name: Main pipeline workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      name:
        description: 'Version name'
        required: true
        type: string

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write
  pages: write
  id-token: write

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Output version
        run: echo "The version is ${{ steps.get_version.outputs.VERSION }}"

  run_tests:
    needs: checkout
    uses: ./.github/workflows/callable.test.yml
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

  publish:
    needs: run_tests
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/callable.publish.yml
    with:
      VERSION: ${{ github.event.inputs.name || 'dev' }}
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      APARTIUM_NEXUS_USERNAME: ${{ secrets.APARTIUM_NEXUS_USERNAME }}
      APARTIUM_NEXUS_PASSWORD: ${{ secrets.APARTIUM_NEXUS_PASSWORD }}

  changelog:
    needs: publish
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/callable.changelog.yml
    with:
      VERSION: ${{ github.event.inputs.name }}
    secrets:
      GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

  docs:
    needs: changelog
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/callable.docs.yml
    with:
      VERSION: ${{ github.event.inputs.name }}
    secrets:
      GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      APARTIUM_NEXUS_USERNAME: ${{ secrets.APARTIUM_NEXUS_USERNAME }}
      APARTIUM_NEXUS_PASSWORD: ${{ secrets.APARTIUM_NEXUS_PASSWORD }}