name: Main pipeline workflow

on:
  pull_request:
  push:
    branches:
      - master
      - '25-rewrite-cicd'
  workflow_dispatch:
    inputs:
      name:
        description: 'Version name'
        required: true
        type: string

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  run_tests:
    needs: checkout
    uses: ./.github/workflows/callable.test.yml

  publish:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Version
        id: set-version
        run: |
          if [ "${{ github.event_name }}" == "push" ] && \
             [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref }}" == "refs/heads/25-rewrite-cicd" ]]; then
            echo "VERSION=${{ github.event.inputs.name }}" >> $GITHUB_ENV
          else
            echo "VERSION=dev" >> $GITHUB_ENV
          fi

      - name: Call Publish Library
        uses: ./.github/workflows/callable.publish.yml
        with:
          VERSION: ${{ env.VERSION }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          APARTIUM_NEXUS_USERNAME: ${{ secrets.APARTIUM_NEXUS_USERNAME }}
          APARTIUM_NEXUS_PASSWORD: ${{ secrets.APARTIUM_NEXUS_PASSWORD }}


  changelog:
    needs: publish
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/callable.changelog.yml

  docs:
    needs: publish
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/callable.docs.yml

  html:
    needs: docs
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/callable.update_html.yml
