name: Pull request CI

on:
  pull_request

jobs:
  unit_test:
    uses: ./.github/workflows/callable.test.yml

  publish:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run integration tests
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}