name: Release

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write
  pages: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Version name'
        required: true
        type: string
